version: 2
updates:
  - package-ecosystem: "npm" # Altere conforme a tecnologia (pip, docker, composer, etc.)
    directory: "/"
    schedule:
      interval: "daily" # Pode ser "daily", "weekly" ou "monthly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
